# Generated by Django 5.1.6 on 2025-03-20 23:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0005_client_gender_alter_client_user'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='customuser',
            name='is_app_admin',
        ),
        migrations.AddField(
            model_name='adminuser',
            name='is_app_admin',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='adminuser',
            name='is_superuser',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='customuser',
            name='is_superuser',
            field=models.BooleanField(default=False, help_text='Designates that this user has all permissions without explicitly assigning them.', verbose_name='superuser status'),
        ),
    ]
