# Generated by Django 5.1.6 on 2025-03-21 00:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0006_remove_customuser_is_app_admin_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='adminuser',
            name='is_app_admin',
        ),
        migrations.RemoveField(
            model_name='adminuser',
            name='is_superuser',
        ),
        migrations.AddField(
            model_name='customuser',
            name='is_app_admin',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='customuser',
            name='is_superuser',
            field=models.BooleanField(default=False),
        ),
    ]
