# Generated by Django 5.1.6 on 2025-03-23 02:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0006_client_profile_picture_customuser_user_type_and_more'),
        ('api', '0007_remove_adminuser_is_app_admin_and_more'),
    ]

    operations = [
    ]
