# Generated by Django 5.1.6 on 2025-04-21 22:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0009_passwordresettoken'),
    ]

    operations = [
        migrations.AddField(
            model_name='serviceowner',
            name='admin_notes',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='serviceowner',
            name='is_approved',
            field=models.BooleanField(default=False),
        ),
    ]
