# Generated by Django 5.1.6 on 2025-04-22 17:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0010_serviceowner_admin_notes_serviceowner_is_approved'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='serviceowner',
            name='admin_notes',
        ),
        migrations.RemoveField(
            model_name='serviceowner',
            name='is_approved',
        ),
    ]
