# Generated by Django 5.1.6 on 2025-04-23 12:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0011_remove_serviceowner_admin_notes_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='serviceowner',
            name='status',
            field=models.CharField(choices=[('pending', 'Pending'), ('approved', 'Approved'), ('rejected', 'Rejected')], default='pending', max_length=10),
        ),
    ]
