# Generated by Django 5.1.6 on 2025-04-23 13:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0012_serviceowner_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='serviceowner',
            name='rejection_reason',
            field=models.TextField(blank=True, null=True),
        ),
    ]
