# Generated by Django 5.1.6 on 2025-04-24 23:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0013_serviceowner_rejection_reason'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='customuser',
            name='is_app_admin',
        ),
        migrations.AlterField(
            model_name='customuser',
            name='user_type',
            field=models.CharField(choices=[('client', 'Client'), ('service_owner', 'Service Owner'), ('admin', 'Admin'), ('superuser', 'Superuser')], default='client', max_length=20),
        ),
    ]
