# Generated by Django 5.1.6 on 2025-04-25 23:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0015_eventtype'),
    ]

    operations = [
        migrations.AddField(
            model_name='serviceowner',
            name='event_types',
            field=models.ManyToManyField(to='api.eventtype'),
        ),
    ]
