# Generated by Django 5.1.6 on 2025-05-10 17:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0018_alter_serviceowner_options_serviceowner_created_at_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='serviceowner',
            options={},
        ),
        migrations.RemoveField(
            model_name='serviceowner',
            name='created_at',
        ),
        migrations.RemoveField(
            model_name='serviceowner',
            name='updated_at',
        ),
        migrations.AlterField(
            model_name='serviceowner',
            name='event_types',
            field=models.ManyToManyField(to='api.eventtype'),
        ),
        migrations.DeleteModel(
            name='Reservation',
        ),
    ]
