# Generated by Django 5.1.6 on 2025-05-10 18:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0019_alter_serviceowner_options_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='serviceowner',
            name='max_budget',
            field=models.DecimalField(decimal_places=2, default=0, help_text='Maximum price for this service', max_digits=10),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='serviceowner',
            name='max_capacity',
            field=models.PositiveIntegerField(blank=True, help_text='Maximum number of people served (if applicable)', null=True),
        ),
        migrations.AddField(
            model_name='serviceowner',
            name='min_budget',
            field=models.DecimalField(decimal_places=2, default=0, help_text='Minimum price for this service', max_digits=10),
            preserve_default=False,
        ),
    ]
